[package]
name = "router_vara_dex"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gstd.workspace = true
sails-rs.workspace = true
log.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true